### PR TITLE
tr_TR.ts

### PR DESCRIPTION
**Pull request by cmhrky**

### CODE REVIEW

**Comment by FelixdelasPozas** [comment]
Hi @cmhrky , thank you very much for your translation! I'll add it to a new release as soon as possible. A few questions:
* Do you want to be credited? (In the About dialog there is a tab with the available translations and the name of the translators). I will need your name if you want to but I will respect if you don't (it will then appear as **cmhrky**).
* The text that would appear in the Language combo box (with the country flag) should be **Türk**, is that correct?

Regards, 
Félix.

**Comment by cmhrky** [comment]
Hi,

You can use my username, my name or both.
Actually **Türkçe**.

**Comment by FelixdelasPozas** [comment]
Hi @cmhrky .

Some texts are missing, could you provide a translation? The texts are:
* Error: 
* No geolocation.
* No pollution data.
* No UV data.
* No weather data.
* Error requesting weather data.
* Error requesting air quality data.
* Error requesting ultraviolet radiation data.

I will update the translation and make a release as soon as possible.

Thanks, 
Félix.

**Comment by cmhrky** [comment]
> - Error:
> - No geolocation.
> - No pollution data.
> - No UV data.
> - No weather data.
> - Error requesting weather data.
> - Error requesting air quality data.
> - Error requesting ultraviolet radiation data.

- Hata:
- Coğrafi konum yok.
- Kirlilik verisi yok.
- UV verisi yok.
- Hava durumu verisi yok.
- Hava durumu verileri istenirken hata oluştu.
- Hava kalitesi verileri istenirken hata oluştu.
- Ultraviyole radyasyon verileri istenirken hata oluştu.

**Comment by FelixdelasPozas** [comment]
The version 1.26 of the application with your translation [have been released](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.26). Many thanks!

Regards, 
Félix.

**Pull request merged**
